### ISSUE TITLE
Values starting with $ are not detected

### ISSUE THREAD

**Issue by erwinc1** [Skyscanner/whispers#108]
Let's say I have a file that contains:

`password: $ecret
`
And I use the following rule:

```
password:
  description: Variable names referring to passwords
  message: Password
  severity: CRITICAL
  key:
    regex: ^\S*(passwords?|passwd|pass|pwd)_?(hash)?[0-9]*$
    ignorecase: True
    isAscii: True
  value:
    isUri: False
```

Why does it not detect `$secret`? If it's `s$cret` it will be detected.
