### ISSUE TITLE
Config.yml does not work

### ISSUE THREAD

**Issue by cosad3s** [Skyscanner/whispers#150]
I have a simple config.yaml:

```yaml
rules:
  oauth: 
    description: OAuth attributes
    message: OAuth
    severity: MAJOR
    key:
      regex: .*(client_id|client_secret).*$
      ignorecase: True
```

My Python code:

```python
import whispers

print("Scan file file.txt")
for secret in whispers.secrets(f"--config config.yml --rules oauth file.txt"):
    print(secret)
```

The scanned file:

```
client_secret=test
```

**No secret is detected / displayed.**

Maybe I do not clearly understand how to use config file ?

Thanks
